#ifndef QJVMHELPER_GLOBAL_H
#define QJVMHELPER_GLOBAL_H

#if defined(QJVMHELPER_LIBRARY)
#  define QJVMHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QJVMHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QJVMHELPER_GLOBAL_H
